apiVersion: v1
kind: Service
metadata:
  name: product-service-naive
  labels:
    app: product-service-naive
spec:
  selector:
    app: product-service-naive
  ports:
    - name: http
      port: 8001
      targetPort: 8001
